//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerSpecsList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputerSpecsList()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int modelID { get; set; }
        public string modelNumber { get; set; }
        public string manufacturer { get; set; }
        public string HD_Type { get; set; }
        public string HD_Capacity { get; set; }
        public string Ram { get; set; }
        public string CPU { get; set; }
        public string DVIPorts { get; set; }
        public string VGAPorts { get; set; }
        public string DisplayPorts { get; set; }
        public string HDMIPorts { get; set; }
        public string USBPorts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
