//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInventoryListing
    {
        public string itemName { get; set; }
        public string tag { get; set; }
        public string serialNumber { get; set; }
        public string modelNumber { get; set; }
        public string CategoryName { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> dateAssigned { get; set; }
        public Nullable<System.DateTime> dateRecordModified { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> datePurchased { get; set; }
        public int itemID { get; set; }
        public Nullable<int> officeID { get; set; }
        public Nullable<int> assignedTo { get; set; }
        public string employeeName { get; set; }
    }
}
